---

- name: VIPS | Installing required dependencies
  apt:
    pkg: "{{ vips_required_libs }}"
    state: present

- name: VIPS | Installing optional dependencies
  apt:
    pkg: "{{ vips_optional_dependencies }}"
    state: present

- name: VIPS | Download sources package
  get_url:
    url: "{{ vips_sources_url }}"
    dest: "{{ vips_tmp }}"

- name: VIPS | Extract sources package
  unarchive:
    copy: false
    src: "{{ vips_tmp }}/{{ vips_sources_package }}"
    dest: "{{ vips_root_path }}"

- name: VIPS | Define compile-time switches
  set_fact:
    vips_compile_time_options_str: "{{ vips_compile_time_options_str | default('') }} {{ '--' + item }}"
  loop: "{{ vips_compile_time_switches }}"

- name: VIPS | Configure installation
  command: ./configure {{ vips_compile_time_options_str | default('') }}
  args:
    chdir: "{{ vips_root_path }}/vips-{{ vips_version }}"

- name: VIPS | Build from sources
  command: "{{ item }}"
  args:
    chdir: "{{ vips_root_path }}/vips-{{ vips_version }}"
  with_items:
    - make
    - make install
  tags:
    skip_ansible_lint

- name: VIPS | Update glib headers
  shell: cp /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h /usr/include; ldconfig
  changed_when: false
