---

- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Build Docker Image
      docker_image:
        path: "."
        name: "idealista/vips"

    - name: Create Docker container
      docker_container:
        name: "vips"
        hostname: "vips"
        image: "idealista/vips"
        privileged: true

    - name: Add container to in-memory inventory
      add_host:
        name: "vips"
        ansible_connection: docker

# Due an Ansible Bug it's not possible to execute this task using "delegate_to" in play defined before
# because was launched using "connection: local" :(
- name: Execute Vips role in Docker container
  hosts: vips
  roles:
    - vips_role
  vars:
    # Using https://github.com/lovell/sharp-libvips/blob/576a4bf211dc15d17071d18090938fcf2afcc977/build/lin.sh#L4 as reference
    vips_optional_dependencies:
      - "libjpeg62-turbo-dev"
      - "zlib1g-dev"
      - "libffi-dev"
      - "libglib2.0-dev"
      - "libxml2-dev"
      - "libgsf-1-dev"
      - "libexif-dev"
      - "liblcms2-dev"
      - "libpng-dev"
      - "libwebp-dev"
      - "libtiff-dev"
      - "liborc-0.4-dev"
      - "libfreetype6-dev"
      - "libfontconfig1-dev"
      - "libharfbuzz-dev"
      - "libpixman-1-dev"
      - "libcairo2-dev"
      - "libfribidi-dev"
      - "libpango1.0-dev"
      - "librsvg2-dev"
      - "libgif-dev"

    vips_compile_time_switches:
      - "enable-shared"
      - "disable-static"
      - "disable-dependency-tracking"
      - "disable-debug"
      - "disable-introspection"
      - "without-python"
      - "without-fftw"
      - "without-magick"
      - "without-pangoft2"
      - "without-ppm"
      - "without-analyze"
      - "without-radiance"

- name: Deploy to Docker Hub
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Commit container file changes to new image
      command: docker commit \
        vips idealista/vips

    - name: Log into Docker Hub
      docker_login:
        email: "{{ docker_hub_email }}"
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Tag and push to Docker Hub
      command: docker push idealista/vips:latest

    - name: Remove the container
      docker_container:
        name: "vips"
        state: absent
